### ISSUE TITLE
Value Mapping

### ISSUE THREAD

**Issue by tkm2016** [Open-Future-Belgium/zabbix#1]
Hello,

The import of the zabbix template Triumph-Adler xml fails because it is missing the value mappings.

Do you have a list of this mappings?

Thanks in advance. 
Thomas

**Comment by Trikke76** [comment]
this is a zabbix issue not an issue with the template
you can look in the template what the value mappings are
and add them manually before importing the template
in zabbix 3.0 this issue should be fixed

**Comment by tkm2016** [comment]
Thank you very much for your replay!
Thomas
