### ISSUE TITLE
import failed zabbix appliance 3.4

### ISSUE THREAD

**Issue by mrvamp** [Open-Future-Belgium/zabbix#3]
i got this error trying to import, can you please assist?
Cannot import template "Template Riverbed Steelhead", linked templates "Template ICMP Ping, Template SNMP Interfaces" do not exist.

**Comment by Trikke76** [comment]
Hi 

it means you are missing Template ICMP Ping, Template SNMP Interfaces
the riverbed template is linked to both
you can also try to delete Template linkage when importing

**Comment by mrvamp** [comment]
Thanks a lot Patrik, let me check .


Regards


Pedro Estrada

________________________________
De: Patrik Uytterhoeven <notifications@github.com>
Enviado: martes, 31 de octubre de 2017 06:25:54 a. m.
Para: Open-Future-Belgium/zabbix
CC: mrvamp; Author
Asunto: Re: [Open-Future-Belgium/zabbix] import failed zabbix appliance 3.4 (#3)


Hi

it means you are missing Template ICMP Ping, Template SNMP Interfaces
the riverbed template is linked to both
you can also try to delete Template linkage when importing
